channels:
- conda-forge
- pytorch
dependencies:
- python=3.7
- numpy==1.18.5
- libffi=3.3
- pip:
  - azureml-core==1.36.0.post2
  - azureml-mlflow==1.36.0
  - azureml-dataset-runtime==1.36.0
  - azureml-telemetry==1.36.0
  - azureml-responsibleai==1.36.0
  - azureml-automl-core==1.36.1
  - azureml-automl-runtime==1.36.1
  - azureml-train-automl-client==1.36.0
  - azureml-defaults==1.36.0
  - azureml-interpret==1.36.0
  - azureml-train-automl-runtime==1.36.1
  - azureml-automl-dnn-vision==1.36.1
  - azureml-dataprep>=2.24.4
  - pillow
- pytorch==1.7.1
- torchvision==0.8.2
name: automl-images-env
